### ISSUE TITLE
chrome 和firefox 上的两个异常

### ISSUE THREAD

**Issue by licess** [Lafeng/ezgoo#36]
同一台电脑上一个chrome正常，另一个chrome报错，报错信息：Error: nid not found，日志信息如下

I0105 08:31:51.200965    6147 config.go:365] DomainRestriction count=5
I0105 08:31:51.201438    6147 config.go:366] ClientRestriction AL=[zh] UA=[Apple] CIDR=0
I0105 08:31:51.204461    6147 server.go:148] Listen at 127.0.0.1:8090
I0105 08:32:05.890511    6147 ezgoo.go:298] 123.123.123.69 GET Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.64 Safari/537.36 [302] https://www.google.com/
E0105 08:32:05.983430    6147 utils.go:54] Error: nid not found
main.dumpError():0x40e520
        /root/go/src/github.com/Lafeng/ezgoo/utils.go:54
main.(*Session).avoidCountryRedirect.func1():0x40eb90
        /root/go/src/github.com/Lafeng/ezgoo/prefdom.go:22
runtime.call32():0x46bbe0
        /usr/local/go/src/runtime/asm_amd64.s:437
runtime.gopanic():0x43b730
        /usr/local/go/src/runtime/panic.go:423
main.setPrefDom():0x40a940
        /root/go/src/github.com/Lafeng/ezgoo/prefdom.go:69
main.(*Session).avoidCountryRedirect():0x40a870
        /root/go/src/github.com/Lafeng/ezgoo/prefdom.go:31
main.(*Session).doProxy():0x406eb0
        /root/go/src/github.com/Lafeng/ezgoo/ezgoo.go:320
main.(*ezgooServer).ServeHTTP():0x404a80
        /root/go/src/github.com/Lafeng/ezgoo/ezgoo.go:75
net/http.serverHandler.ServeHTTP():0x4f8080
        /usr/local/go/src/net/http/server.go:1863
net/http.(*conn).serve():0x4f4e80
        /usr/local/go/src/net/http/server.go:1362
runtime.goexit():0x46df70
        /usr/local/go/src/runtime/asm_amd64.s:1722
		
		
		
使用firefox时会提示：Error: Not allowed
日志里信息为：I0105 08:34:42.697444    6206 config.go:365] DomainRestriction count=5
I0105 08:34:42.697696    6206 config.go:366] ClientRestriction AL=[zh] UA=[Apple] CIDR=0
I0105 08:34:42.700010    6206 server.go:148] Listen at 127.0.0.1:8090
I0105 08:34:45.901576    6206 ezgoo.go:69] 123.123.123.69 GET Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0 [PASS] /

**Comment by vickery** [comment]
1、加上启动参数`-v3 -debug`，然后在另一个chrome上打开，并清理cookie，然后把错误前后的详细日志贴出来
2、因为示例的配置中有`UserAgent = Apple`，要让firefox可访问就把这个置空

**Comment by licess** [comment]
感谢，firefox的解决了

1问题按你要求操作后的日志如下：
ezgoo -dir dist -v 3 -debug
I0105 12:48:50.089262   11533 config.go:365] DomainRestriction count=5
I0105 12:48:50.089503   11533 config.go:366] ClientRestriction AL=[zh] UA=[] CIDR=0
I0105 12:48:50.091773   11533 server.go:148] Listen at 127.0.0.1:8090
  <- Header/ActualReq
     Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
     Accept-Encoding: gzip
     Accept-Language: en,zh-CN;q=0.8,zh;q=0.6
     Upgrade-Insecure-Requests: 1
     User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.64 Safari/537.36
     Connection: keep-alive
I0105 12:48:57.512831   11533 ezgoo.go:298] 123.169.119.69 GET Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.64 Safari/537.36 [302] https://www.google.com/
  -> Header/OriginalResp
     Content-Type: text/html; charset=UTF-8
     Location: https://www.google.com.hk/?gfe_rd=cr&ei=vkqLVsbXMvLC8AeD2brgBQ
     Content-Length: 263
     Date: Tue, 05 Jan 2016 04:46:54 GMT
     Server: GFE/2.0
     Alternate-Protocol: 443:quic,p=1
     Alt-Svc: quic="www.google.com:443"; ma=600; v="30,29,28,27,26,25",quic=":443"; ma=600; v="30,29,28,27,26,25"
     Cache-Control: private
  resp[400 Bad Request]->https://www.google.com/setprefdomain?prefdom=US&prev=https%3A%2F%2Fwww.google.com%2F%3Fgfe_rd%3Dcr%26gws_rd%3Dcr&sig=0_dYrMftJ5Jgqnf26Hhqr8ZZ85aVs%3D" style="left:-1000em;position:absolute">Screen reader users, click here to turn off Google Instant.</a>  <textarea name="csi" id="csi" style="display:none"></textarea><script>if(google.j.b)document.body.style.visibility='hidden';</script><div class="jhp" id="searchform"><script>(function(){var _j=1250;try{var s=document.getElementById('searchform');var w=document['body']
     Content-Type: text/html; charset=UTF-8
     Content-Length: 1555
     Date: Tue, 05 Jan 2016 04:46:54 GMT
     Server: GFE/2.0
E0105 12:48:57.621352   11533 utils.go:54] Error: nid not found
main.dumpError():0x40e520
        /root/go/src/github.com/Lafeng/ezgoo/utils.go:54
main.(*Session).avoidCountryRedirect.func1():0x40eb90
        /root/go/src/github.com/Lafeng/ezgoo/prefdom.go:22
runtime.call32():0x46bbe0
        /usr/local/go/src/runtime/asm_amd64.s:437
runtime.gopanic():0x43b730
        /usr/local/go/src/runtime/panic.go:423
main.setPrefDom():0x40a940
        /root/go/src/github.com/Lafeng/ezgoo/prefdom.go:69
main.(*Session).avoidCountryRedirect():0x40a870
        /root/go/src/github.com/Lafeng/ezgoo/prefdom.go:31
main.(*Session).doProxy():0x406eb0
        /root/go/src/github.com/Lafeng/ezgoo/ezgoo.go:320
main.(*ezgooServer).ServeHTTP():0x404a80
        /root/go/src/github.com/Lafeng/ezgoo/ezgoo.go:75
net/http.serverHandler.ServeHTTP():0x4f8080
        /usr/local/go/src/net/http/server.go:1863
net/http.(*conn).serve():0x4f4e80
        /usr/local/go/src/net/http/server.go:1362
runtime.goexit():0x46df70
        /usr/local/go/src/runtime/asm_amd64.s:1722

**Comment by vickery** [comment]
pull同步然后编译。

**Comment by licess** [comment]
还是Error: nid not found的错误
ezgoo -dir dist -v 3 -debug
I0105 13:22:46.717644   12463 config.go:365] DomainRestriction count=5
I0105 13:22:46.717930   12463 config.go:366] ClientRestriction AL=[zh] UA=[] CIDR=0
I0105 13:22:46.720302   12463 server.go:148] Listen at 127.0.0.1:8090
  <- Header/ActualReq
     Connection: keep-alive
     Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
     Upgrade-Insecure-Requests: 1
     User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.64 Safari/537.36
     Accept-Encoding: gzip
     Cache-Control: no-cache
     Accept-Language: en,zh-CN;q=0.8,zh;q=0.6
     Pragma: no-cache
I0105 13:22:50.777741   12463 ezgoo.go:298] 123.123.123.69 GET Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.64 Safari/537.36 [302] https://www.google.com/
  -> Header/OriginalResp
     Content-Length: 263
     Date: Tue, 05 Jan 2016 05:20:48 GMT
     Server: GFE/2.0
     Alternate-Protocol: 443:quic,p=1
     Alt-Svc: quic="www.google.com:443"; ma=600; v="30,29,28,27,26,25",quic=":443"; ma=600; v="30,29,28,27,26,25"
     Cache-Control: private
     Content-Type: text/html; charset=UTF-8
     Location: https://www.google.com.hk/?gfe_rd=cr&ei=sFKLVtGJAu7C8AfGsLTYCg
  resp[302 Found]->https://www.google.com/setprefdomain?prefdom=US&prev=https%3A%2F%2Fwww.google.com%2F%3Fgfe_rd%3Dcr%26gws_rd%3Dcr&sig=0_75TT92c3lsCJwpfv_Ci_1--5C8M%3D
     Content-Type: text/html; charset=UTF-8
     Server: gws
     Content-Length: 244
     X-Xss-Protection: 1; mode=block
     X-Frame-Options: SAMEORIGIN
     Location: https://www.google.com/?gfe_rd=cr&gws_rd=cr
     Date: Tue, 05 Jan 2016 05:20:48 GMT
     Alternate-Protocol: 443:quic,p=1
     Alt-Svc: quic="www.google.com:443"; ma=600; v="30,29,28,27,26,25",quic=":443"; ma=600; v="30,29,28,27,26,25"
     Cache-Control: private
E0105 13:22:50.912633   12463 utils.go:54] Error: nid not found
main.dumpError():0x40e520
        /root/go/src/github.com/Lafeng/ezgoo/utils.go:54
main.(*Session).avoidCountryRedirect.func1():0x40eb90
        /root/go/src/github.com/Lafeng/ezgoo/prefdom.go:22
runtime.call32():0x46bbe0
        /usr/local/go/src/runtime/asm_amd64.s:437
runtime.gopanic():0x43b730
        /usr/local/go/src/runtime/panic.go:423
main.setPrefDom():0x40a940
        /root/go/src/github.com/Lafeng/ezgoo/prefdom.go:69
main.(*Session).avoidCountryRedirect():0x40a870
        /root/go/src/github.com/Lafeng/ezgoo/prefdom.go:31
main.(*Session).doProxy():0x406eb0
        /root/go/src/github.com/Lafeng/ezgoo/ezgoo.go:320
main.(*ezgooServer).ServeHTTP():0x404a80
        /root/go/src/github.com/Lafeng/ezgoo/ezgoo.go:75
net/http.serverHandler.ServeHTTP():0x4f8080
        /usr/local/go/src/net/http/server.go:1863
net/http.(*conn).serve():0x4f4e80
        /usr/local/go/src/net/http/server.go:1362
runtime.goexit():0x46df70
        /usr/local/go/src/runtime/asm_amd64.s:1722

**Comment by vickery** [comment]
清理你的域名的下的cookie, local storage等等。
如果还不行，执行
```
curl -A "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) " -H "Accept-Language: zh" -c cookie.tmp -i -L  http(s)://your_domain
```
把这个输出和服务端的一同贴出来，用\`\`\`做片段头尾包起来。

**Comment by licess** [comment]
curl结果```
HTTP/1.1 302 Found                                                 
Server: nginx                                                      
Date: Tue, 05 Jan 2016 06:31:41 GMT                                
Content-Type: text/html; charset=UTF-8                             
Content-Length: 0                                                  
Connection: keep-alive                                             
Location: /                                                        
Set-Cookie: NID=75=O91Sbs8mvWQ_RvQOpJpLgldhkJCwbDQb8411V4SwMlFXTxx5
K4qYn16_tnhn5Cg4y634vVLPA; Path=/; Expires=Wed, 06 Jul 2016 06:29:3
X-Cache: MISS                                                      
                                                                   
HTTP/1.1 200 OK                                                    
Server: nginx                                                      
Date: Tue, 05 Jan 2016 06:31:41 GMT                                
Content-Type: text/html; charset=UTF-8                             
Transfer-Encoding: chunked                                         
Connection: keep-alive                                             
Cache-Control: private, max-age=0                                  
Content-Encoding: gzip                                             
Expires: -1                                                        
X-Frame-Options: SAMEORIGIN                                        
X-Xss-Protection: 1; mode=block                                    
X-Cache: MISS                                                      
                                                                   
▼?      n? 探iw茇u(鷀竣埗〣‼珺Md眾►↨%?灯周M裓C☻♣►@qP┲rn灀8/蝩n湜蒠+N熵k?w^^顁n:v~蘫
```
服务端信息如下
```
I0105 14:31:20.928165   14043 config.go:365] DomainRestriction count=5
I0105 14:31:20.928596   14043 config.go:366] ClientRestriction AL=[zh] UA=[] CIDR=0
I0105 14:31:20.932151   14043 server.go:148] Listen at 127.0.0.1:8090
  <- Header/ActualReq
     Accept-Encoding: gzip
     User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
     Accept: */*
     Accept-Language: zh
     Connection: keep-alive
I0105 14:31:41.213314   14043 ezgoo.go:298] 123.123.123.69 GET Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) [302] https://www.google.com/
  -> Header/OriginalResp
     Content-Length: 263
     Date: Tue, 05 Jan 2016 06:29:38 GMT
     Server: GFE/2.0
     Alternate-Protocol: 443:quic,p=1
     Alt-Svc: quic="www.google.com:443"; ma=600; v="30,29,28,27,26,25",quic=":443"; ma=600; v="30,29,28,27,26,25"
     Cache-Control: private
     Content-Type: text/html; charset=UTF-8
     Location: https://www.google.com.hk/?gfe_rd=cr&ei=0mKLVr7vFMrC8Ae66rSADA
  <- Header/ActualReq
     Accept-Encoding: gzip
     Connection: keep-alive
     User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
     Accept: */*
     Accept-Language: zh
     Cookie: NID=75=O91Sbs8mvWQ_RvQOpJpLgldhkJCwbDQb8411V4SwMlFXTxx50Z3CMs9E6YfGFDDYjwAJYkMn00kpF7S3YuQZj6SW7VFQM9olFTexp6zROgwoqqLkrWlkK9UiwK4qYn16_tnhn5Cg4y634vVLPA
I0105 14:31:41.444433   14043 ezgoo.go:298] 123.123.123.69 GET Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) [200] https://www.google.com/
  -> Header/OriginalResp
     Expires: -1
     Cache-Control: private, max-age=0
     Server: gws
     X-Xss-Protection: 1; mode=block
     Alternate-Protocol: 443:quic,p=1
     Date: Tue, 05 Jan 2016 06:29:38 GMT
     Content-Type: text/html; charset=UTF-8
     Content-Encoding: gzip
     X-Frame-Options: SAMEORIGIN
     Alt-Svc: quic="www.google.com:443"; ma=600; v="30,29,28,27,26,25",quic=":443"; ma=600; v="30,29,28,27,26,25"```

**Comment by vickery** [comment]
很明显curl请求200OK已经成功了，也没有任何异常发生，还有什么问题？

**Comment by licess** [comment]
出问题的那个chrome访问还是提示Error: nid not found，cookie各种缓存都选上清空了也不行，就直接去chrome目录下删了些tmp文件，现在已经好了，谢谢
