### ISSUE TITLE
部署时出现异常 error: reference to undefined field or method ‘MatchRunePos’

### ISSUE THREAD

**Issue by ZRStea** [Lafeng/ezgoo#37]
在ubuntu14.04下执行`go get github.com/Lafeng/ezgoo`
提示
`go/src/github.com/Lafeng/ezgoo/regexp/onepass.go:70:11: error: reference to undefined field or method ‘MatchRunePos’`
`next := i.MatchRunePos(r)`

**Comment by vickery** [comment]
go version ?

**Comment by ZRStea** [comment]
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

**Comment by vickery** [comment]
golang.org/dl 下载最新的版本

**Comment by ZRStea** [comment]
谢谢 我去尝试一下
